#!/bin/bash

declare -a mesh_size
mesh_size=( 50 100 200 300 400 )

##################################################################
# make run dir if not present

mkdir -p test_cases/run

####################################################################
# copy base_case and in run directory it modified and run and copied
####################################################################

cp -r test_cases/cylinder2D_base test_cases/run/

declare -i j
j=1
len=${#mesh_size[@]}
 
for ((k=1;k<=$len;k++)); do
    mkdir -p notebooks/plot_data/cases/case_$k
done
	
for i in "${mesh_size[@]}"
do
	cd ./test_cases/run/cylinder2D_base/
	echo -e "******************************************************************"
	echo -e "\nMesh size = $i\n"
	echo -e "******************************************************************"
	./Allclean
	./mesh bmcell $i
	./solveronly
	cd .. ; cd .. ; cd ..
	cp -r test_cases/run/cylinder2D_base/system notebooks/plot_data/cases/case_$j
	cp -r test_cases/run/cylinder2D_base/postProcessing notebooks/plot_data/cases/case_$j
	let "j++"
done
