#!/usr/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp -r 0.org 0
runApplication setExprBoundaryFields
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel $(getApplication)

